### ISSUE TITLE
台账中可编辑的地方目前还是提示英文，需改为中文

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#103]
![image](https://user-images.githubusercontent.com/7665279/68010034-7517f180-fcbe-11e9-8741-4c08a9a16d16.png)

**Comment by huangyiirene** [comment]
![微信图片_20191106134336](https://user-images.githubusercontent.com/7665279/68271451-7e78d380-009b-11ea-8bd0-3362affcab81.jpg)

**Comment by baozhoutao** [comment]
https://github.com/steedos/creator/commit/a61bfc599a2d13eb5519b5670ff07be6a74f744a
