### ISSUE TITLE
确认锁定locked功能

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-project-dzug#127]
普通用户
- [x] 列表页双击字段不能编辑
- [x] 详细页双击字段不能编辑
- [x] 列表和详细页都不显示编辑和删除按钮
- [x] 详细页附件禁止新增、编辑、删除、上传新版本
- [x] 服务端不做控制

管理员不做控制（拥有对象的modifyAll权限）

**Comment by hotlong** [comment]
参考 https://github.com/steedos/creator/issues/930

**Comment by yinlianghui** [comment]
测试结果：
- 其他都是好的，只有附件有点小问题
- 详细页附件列表中名称字段级编辑未禁用
- 详细页附件列表点开查看附件详细，弹出的附件详细界面中名称入描述字段级编辑未禁用
