### ISSUE TITLE
审批单和业财台账中，收款计划和付款计划中的收款单位 付款单位的选择范围是否可圈定在选择的签约对象中

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#137]

**Comment by baozhoutao** [comment]
**申请单字段脚本：将申请单的收款单位，付款单位设置为odata类型， 将以下脚本拷贝到过滤条件中**
```
function(partner_names){
    var qydxIds = _.compact(_.uniq(_.pluck(_.pluck(partner_names,"qydx_name"), "_id")));

    if(qydxIds.length < 1){
        return "(_id eq 'notFindQydx')"
    }

    var filters = [];

    _.forEach(qydxIds, function(qydxId){
        filters.push("(_id eq '" + qydxId + "')")
    })

    return filters.join(" or ")
}
```

**Comment by baozhoutao** [comment]
**流程自定义脚本：提交申请单时，校验收付款计划的收款方，付款方是否包含在签约对象中**
$(".instance-form").on('instance-before-submit', function(e) {
    var formValues = AutoForm.getFormValues("instanceform").insertDoc;
    var qydxIds = _.compact(_.uniq(_.pluck(_.pluck(formValues.partner_names,"qydx_name"), "_id"))); 
    var fkjh_skf = _.compact(_.uniq(_.pluck(_.pluck(formValues["付款计划"],"收款方"), "_id"))); 
    var skjh_fkf = _.compact(_.uniq(_.pluck(_.pluck(formValues["收款计划"],"付款方"), "_id"))); 
    if(_.difference(fkjh_skf, qydxIds).length > 0){
        e.preventDefault();
        toastr.warning('付款计划的收款方必须包含在签约对象中');
    }
    if(_.difference(skjh_fkf, qydxIds).length > 0){
        e.preventDefault();
        toastr.warning('收款计划的付款方必须包含在签约对象中');
    }
})
