### ISSUE TITLE
收付款登记流程中选择签约对象的框需调长

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#152]
![image](https://user-images.githubusercontent.com/7665279/68921742-a6131e80-07b4-11ea-8067-25fd706f4b22.png)

**Comment by huangyiirene** [comment]
![image](https://user-images.githubusercontent.com/7665279/69394825-115e7280-0d18-11ea-9ba4-26b5a3fb4c3a.png)
可参考此长度

**Comment by baozhoutao** [comment]
配置表单脚本即可： 流程设计器 -> 表单 ->表单脚本
```
CoreForm.子表名称= {};
CoreForm.子表名称.onload = function(){
    $(".steedos-table-modal-body").css("min-height",'300px');
}
```

**Comment by baozhoutao** [comment]
https://github.com/steedos/workflow/issues/2076
