### ISSUE TITLE
当页面弹出窗口太小时，页面显示为手机界面

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#166]
![image](https://user-images.githubusercontent.com/7665279/69019032-d68fce00-09e9-11ea-8cf5-0ac3e3b227e7.png)

**Comment by yinlianghui** [comment]
- dzug的审批王顶部导航
![image](https://user-images.githubusercontent.com/6219465/72495461-c10c1880-3861-11ea-93ea-d6665db3b128.png)
- dzug的eip门户入口
![image](https://user-images.githubusercontent.com/6219465/72495475-c9fcea00-3861-11ea-9495-05c4313e1bfb.png)

**Comment by yinlianghui** [comment]
- dzug的审批王顶部导航：已通过增加自定义应用脚本修正该问题（弹出窗口大小与creator平台的新窗口链接中设置的一样），脚本已加到正式平台生效了。
- dzug的eip门户入口：需要他们自己那边门户改代码处理。
- 审批王设置界面中的高级设置链接也修正成一样的了，改的workflow源码下次打包后生效

![image](https://user-images.githubusercontent.com/6219465/72593911-27b43380-3941-11ea-9c1e-21003fb481d3.png)
