### ISSUE TITLE
将大众正式平台升级事宜

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#179]
- [x]  将大众正式平台环境在公司搭建，包括审批王及creator
- [x]  将审批王升级到最新版
- [x]  将creator 升级到二合一版最新版
- [x]   测试审批王各项功能，及数据是否正常
- [x]  测试creator各项功能,及归档系统的功能
- [x]  nc:签约对象导入，更新银行信息
- [x]  odoo:签约对象导入（设为已停用）
- [x]  odoo合同导入，草稿箱中的不导入，进行中的合同需要每天同步，直至流程结束
- [x]  合同附件也需要同步，odoo数据库中fileid字段为空的合同附件手动导入（流水号为17077 17060 17078 17083 17076 17085 17062 17084 17082 17086 17075 17061 17079 17059 17081 17080）

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-project-dzug/issues/128
