### ISSUE TITLE
签约对象是假删除，删除后，重复新建“纳税人识别号”相同的记录会报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-project-dzug#185]
纳税人识别号配置了 unique: true
同时也配置了 enable_trash: true

![image](https://user-images.githubusercontent.com/6219465/69214564-41840500-0ba2-11ea-8629-08aa6bf1a42b.png)

> 目前假删除的记录还没有还原功能

**Comment by sunhaolin** [comment]
去掉删除功能，使用 停用字段处理过滤数据
