### ISSUE TITLE
应收记录中的“客户银行账户”值未显示，值可传到NC，在编辑状态显示

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#195]
显示界面
![image](https://user-images.githubusercontent.com/7665279/69401156-3f9b7c80-0d2f-11ea-84df-30fa2396d8f0.png)
编辑界面
![image](https://user-images.githubusercontent.com/7665279/69401165-488c4e00-0d2f-11ea-9b74-779f2c853675.png)

**Comment by hotlong** [comment]
这个是因为 lookup 对应的记录不存在吗？

**Comment by sunhaolin** [comment]
可能导致：收款记录 | 付款银行账户OA收款记录中无值
