### ISSUE TITLE
二维表，收款记录，将收款日期设置为列，显示异常

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-dzug#225]

**Comment by yinlianghui** [comment]
是因为数据库中有收款日期值为空造成的，手动改数据库过滤条件试了下，过滤掉空值后正常

**Comment by yinlianghui** [comment]
异常情况截图如下：
![image](https://user-images.githubusercontent.com/6219465/71960577-5559f800-3230-11ea-8b48-2d99fe555324.png)

**Comment by yinlianghui** [comment]
- 经排查，是因为按行统计时，某行的数据中同行关联到收款日期为空或不为空的两种记录时才会有问题
- 只能要求收款记录把收款日期字段设置为必填，或者报表中把收款日期设置为必填过滤项了
![image](https://user-images.githubusercontent.com/6219465/75944341-62aefe00-5ed2-11ea-9acc-09b9715c2af0.png)
