### ISSUE TITLE
合同变更执行人后，执行人进入台账未看到此条记录

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#238]
![image](https://user-images.githubusercontent.com/7665279/70209026-11279380-176a-11ea-8001-d3ed3c121dd7.png)
![image](https://user-images.githubusercontent.com/7665279/70209031-1553b100-176a-11ea-8275-7bd60cb19e83.png)

**Comment by sunhaolin** [comment]
待黄怡确认

**Comment by sunhaolin** [comment]
已确认不存在跨单位调整执行人的情况
