### ISSUE TITLE
大众公用工作区，在流程设计器中开启“供应链内部员工调动页面”报错，进入流程具体信息显示已启用，前台发起界面无此流程

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#248]
![image](https://user-images.githubusercontent.com/7665279/70503628-c5585e00-1b5e-11ea-95a0-9a1ab342deb2.png)
![image](https://user-images.githubusercontent.com/7665279/70503636-cab5a880-1b5e-11ea-80ce-3e0883f51f9c.png)

**Comment by sunhaolin** [comment]
初步判断由于此流程是通过导入功能新建的导致

**Comment by huangyiirene** [comment]
重新设置流程发起权限后，流程可正常使用
