### ISSUE TITLE
新推送提示开发

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#252]
1.      收款计划的收款到期提前5日推送提醒给我方单位财务负责人及经营者（手机及电脑端）。 
    提示语：“合同名称”+预计+“计划收/付款日期”+将有+“本次收款金额”+到账
2.      超过计划收款时间（T）30天还未收到款项，向除我方单位财务负责人及经营者之外再加上分管领导、各职能部门（投资、法务、财务）发送推送提醒（T+30）（手机及电脑端） 
3.      超过计划收款时间（T）60天还未收到款项，向集团总裁发送推送提醒（T+60）（手机及电脑端）  
4.      当付款单支付状态为支付成功，“发票是否齐全”字段为否时，向执行人发送推送提醒（手机及电脑端）
提示语： ”合同名称“ + 发票未齐全

**Comment by huangyiirene** [comment]
其中第二点可修改https://github.com/steedos/steedos-project-dzug/issues/167中的第二点，将时间改为30天，并多加关注人员
其于不急开发

**Comment by sunhaolin** [comment]
新建表(notification_type)：有那些通知类型（变化[trigger]，提前5天，超时30天等，超时60天）：
字段：
    name
新建表(notification_user)：那些用户收那些单位的通知 ；一个用户对应一个单位对应多个通知

**Comment by sunhaolin** [comment]
contract_receipts_expiredDay_remindBoss   收款计划超时提醒总裁

**Comment by sunhaolin** [comment]
- [ ] 需要添加通知类型记录：
- 付款计划变化
- 收款计划变化
- 超过计划收款时间30天
- 超过计划收款时间60天
- 提前收款时间5天通知
