### ISSUE TITLE
应收单 应付单 付款单 打印样式

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#288]
![应收单新样式](https://user-images.githubusercontent.com/7665279/71501604-6442c100-28a6-11ea-9bc6-6a7140ee8a14.png)

**Comment by chenzhipei** [comment]
打印模板调整如下：标题宋体10，其他字体宋体6号，A4纸张纵向打印，宽度21，高度29.7

**Comment by yinlianghui** [comment]
[样式附件](https://messenger.steedos.cn/files/7ftft3pg33g59ra9kcwycsmfmy/public?h=4LLtAQKC7jcvAEWISBEPexQwzrlReip0-3QY_aqd8TU)

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/71508370-85b1a600-28c2-11ea-9bc5-2cb382ff4de5.png)

**Comment by yinlianghui** [comment]
经讨论所谓样式统一指的是style样式，不是指字段标题之类的，显示哪些字段以及字段标题变量还是以之前的任务为准！
