### ISSUE TITLE
签约对象中所属单位字段配置了filters属性未生效

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-project-dzug#293]

**Comment by sunhaolin** [comment]
待 https://github.com/steedos/object-server/issues/225 完成后配置filters属性 `filters: [["enablestate", "eq", "2"], ["hidden", "ne", true]]`

**Comment by yinlianghui** [comment]
关联任务：[修改baseObject的company_id(s)字段的optionsFunction，使其兼容用户定义的filters属性，取AND #225](https://github.com/steedos/object-server/issues/225)
这个关联任务处理完后就支持了！

**Comment by yinlianghui** [comment]
关联任务：[考虑lookup控件的filters属性解析统一走@steedos/filters包的解析语法 #1548](https://github.com/steedos/creator/issues/1548)
- 还需要等这个任务处理完成才能支持
- 还需要creator打包，#1548, #225

**Comment by yinlianghui** [comment]
该任务已经可以开始配置了实现了。
- 请使用：`filters: [["enablestate", "=", "2"], ["hidden", "!=", true]]`
- 所有所属单位的company_id/company_ids都支持标准的filters功能，因为走了optionsFunction请求odata
- 关联任务[考虑lookup控件的filters属性解析统一走@steedos/filters包的解析语法 #1548](https://github.com/steedos/creator/issues/1548) 已经关掉了，暂时不处理
