### ISSUE TITLE
增加用户所属单位之后，在用户作为执行人的合同详细页面新建应收记录时收款单位字段选项显示id，而非名称

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-project-dzug#296]
如：
用户a新增所属单位c，合同的我方单位字段也是c

**Comment by yinlianghui** [comment]
- 这个问题刚讨论的不对，不是baseObject中company_id的optionsFunction的bug（函数中用的就是当前登录用户的company_ids来取下拉列表的）
- 经初步判断是因为当前登录用户的company_ids取自服务器的auth缓存，变更用户所属company_ids值后，需要10分钟才能更新缓存取到正确的company_ids值

**Comment by sunhaolin** [comment]
不需要注销，等十分钟后用户刷新页面即可
