### ISSUE TITLE
签约对象权限控制

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-dzug#3]

**Comment by huangyiirene** [comment]
签约对象将按公司级进行管理，默认属于录入人所在的公司，该公司人员在使用时可见，如其他公司合同管理员如添加同一家公司，系统会进行提示，可以请系统管理员，将此签约对象分配给其他需要使用的组织。被共享的签约单位信息，被共享方的管理员不可以修改签约对象信息。具体如下：
 	**查看：**在合同流程使用时，签约对象录入公司，被共享的公司。
在签约对象台账中，录入的合同管理员及其所在公司的领导，被共享的公司的合同管理员及其所在公司的领导，集团合同管理员，指定的集团领导。
 	**新建：**每个公司由合同管理员录入新建签约对象。
 	**修改：**签约对象可由系统管理员进行修改。
 	**删除：**已经被使用过的，即已成为某个合同的签约对象后，不能删除，但可以进行停用。未被使用的签约对象可由最初录入人和系统管理员进行删除。

**Comment by huangyiirene** [comment]
签约对象增加时应不能分配使用单位

**Comment by huangyiirene** [comment]
签约对象下的主单位需可见，单位合同管理员建签约对象时主单位根据所属单位自动赋值，且不可修改，合同管理员和管理员新建签约对象时，主单位根据所属单位自动赋值，但可编辑。

**Comment by chenzhipei** [comment]
11月26(黄怡):一般用户放开新增和编辑权限,不能删除
