### ISSUE TITLE
查找等界面，选择单位，如果单位名称长了，用于取消的"X"不显示

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#307]
![image](https://user-images.githubusercontent.com/6219465/72489566-62d63a00-384f-11ea-97eb-e6235530736b.png)

**Comment by huangyiirene** [comment]
![image](https://user-images.githubusercontent.com/7665279/73722429-6d566600-4761-11ea-9839-8de8c6c8705b.png)
提示需改为中文

**Comment by yinlianghui** [comment]
翻译问题已处理，并增加了鼠标放到选项上时把选项title显示出来的效果
