### ISSUE TITLE
增加发起收付款业务的控制条件

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#329]
- 当合同状态为“已核准”、“已归档”、“已签订“时，”提前付款“字段无论为何值时都可发起后续收付款业务（发起应付记录、付款记录和应收记录）。
 - 当合同状态为“审批中“，”提前付款“字段为”是“时，可由执行人发起收付款业务
”提前付款“字段为”否“时，执行人不可发起收付款业务
 - 当合同状态为“已废止“和“已驳回”时，提前付款“字段无论为何值时都不可以发起后续收付款业务。

**Comment by sunhaolin** [comment]
- [ ] 应付记录 收票时校验
- [ ] 付款记录 申请付款时校验
- [ ] 应收记录 申请开票时校验
