### ISSUE TITLE
付款单的打印界面中，发送人、审批人、审批状况和审批意见字段不要换行，批语可以缩短并换行.并且所有单据中金额字段不要换行，应收单中发票号可以缩短，摘要说明放长宽度

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#330]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/6219465/75011344-5aaa9380-54ba-11ea-94b7-2ff2e17f236d.png">

**Comment by yinlianghui** [comment]
三个打印界面字段宽度已优化，主要是把流水号、金额及数值字段设置为不换行，其他字段自动适应（应收单中发票号摘要字段除外，设置了20%及30%）
