### ISSUE TITLE
账务管理员需对由确认成本和确认收入生成的应收、应付记录有编辑和删除的权限

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#339]

**Comment by sunhaolin** [comment]
- 放开账务管理员对应收、应付记录的编辑权限 modifyAllRecords: true, modifyCompanyRecords:true
- 当前用户是账务管理员并且不是合同执行人时：
  - 当合同业务分类是 房屋租赁（出租方），隐藏应付记录的编辑、删除按钮
  - 当合同业务分类是 房屋租赁（承租方），隐藏应收记录的编辑、删除按钮
