### ISSUE TITLE
业务单元、部门、银行档案、业务分类同步过来时记录启用状态数据，并实现支持启用停用功能

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-project-dzug#42]
审批单中只取启用的数据

**Comment by huangyiirene** [comment]
停用具体体现在审批单选择的值中不显示被停用的内容

**Comment by huangyiirene** [comment]
业务分类还是能看到

**Comment by huangyiirene** [comment]
![image](https://user-images.githubusercontent.com/7665279/68459179-9d17cf80-023f-11ea-91a9-47c59261a654.png)
![image](https://user-images.githubusercontent.com/7665279/68459188-a30db080-023f-11ea-8571-c007dbc06e66.png)
已停用的的银行账号还是能选择到
