### ISSUE TITLE
审批单子表中的字段数据需要同步到creator的合同台账信息中

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#46]

**Comment by huangyiirene** [comment]
![image](https://user-images.githubusercontent.com/7665279/67352785-84db5b80-f583-11e9-8060-2ccd6d42d4b2.png)

**Comment by huangyiirene** [comment]
如果子表字段code与对象相关表表名一致则同步子表数据至相关表，如：instance.values.付款计划对应合同中的contracts 的相关 付款计划表

 objectql中object需要提供方法，返回object的相关表（master_detail）表名；

**Comment by baozhoutao** [comment]
为了实现申请单子表数据同步到creator的相关表，给子表新增_id 属性， 用于解决申请单子表数据与相关表记录的对应关系

**Comment by baozhoutao** [comment]
https://github.com/steedos/creator/issues/1408

**Comment by baozhoutao** [comment]
workflow 版本必须大于：4.6.6
