### ISSUE TITLE
打印界面添加相关记录功能，用于NC可通过审批单查看到台账

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#51]
![image](https://user-images.githubusercontent.com/7665279/66974984-8ca48700-f0cf-11e9-9bce-cb94d8243083.png)

![image](https://user-images.githubusercontent.com/7665279/66975008-a04fed80-f0cf-11e9-9a68-cd44f52078b3.png)

**Comment by baozhoutao** [comment]
https://github.com/steedos/creator/issues/1412
