### ISSUE TITLE
需实现原合同台账中的合同状态功能，审批中-已核准-已驳回-已取消-已签订-已归档-已作废

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#52]
![image](https://user-images.githubusercontent.com/7665279/66975351-d80b6500-f0d0-11e9-9633-deca8ea3481d.png)
审批中：进入审批过程
已核准：审批单已核准
已驳回：审批单被驳回
已取消：取消申请的流程
已签订：在原件管理中填写了签订日期
已归档：在原件管理中勾选“原件”或者“扫描件”、“复印件”的三者之一
已作废：在原件管理中填写了废止日期

在 申请单已核准到结束之后 才修改 已签订、已归档、已作废状态

**Comment by hotlong** [comment]
在触发器中判断修改了对应的字段，更新合同状态。

**Comment by sunhaolin** [comment]
在 申请单已核准到结束之后 才修改 已签订、已归档、已作废状态
