### ISSUE TITLE
新建相关记录的时候，可以带上一些于主表相同的字段作为默认值 

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#59]
应收 应付 付款单中的收款单位 付款单位和币种是否可以从合同信息中根据收款/付款合同，取值，用户也可自己编辑

**Comment by hotlong** [comment]
新建相关记录的时候，可以带上一些于主表相同的字段作为默认值 #1401

**Comment by baozhoutao** [comment]
通过object.form.initialValues 实现此需求
