### ISSUE TITLE
应收单、应付单、付款单打印

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#69]
NC已给视图

**Comment by hotlong** [comment]
需要对方提供打印样式，并签字确认。

**Comment by huangyiirene** [comment]
[单据打印模板.docx](https://github.com/steedos/steedos-project-dzug/files/3796661/default.docx)

**Comment by yinlianghui** [comment]
缺少字段：
1. 付款单v_ap_paybill
业务员所属部门

**Comment by hotlong** [comment]
所有子表需要提供视图

**Comment by yinlianghui** [comment]
子表显示字段：
1. 付款单v_ap_paybill
```
let subFields = ["BCONTRACTNO", "BSCOMMENT", "BMONEY_DE", "BLOCAL_MONEY_DE", "BSUBJCODE"];
```

2. 应付单v_ap_payablebill


3. 应收单v_ar_recbill
