### ISSUE TITLE
签约对象添加时需根据纳税人识别号进行校验，不允许重复添加

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#70]
字段配置为
    unique: true
测试确认一下

**Comment by chenzhipei** [comment]
db.getCollection('accounts').find({credit_code:{$exists:true}}).forEach(function(a){
    var count = 0;
    count = db.accounts.find({credit_code:a.credit_code}).count();
    if (count > 1){
        print(a.name);
        db.accounts.remove({_id:a._id})
    }
})
