### ISSUE TITLE
大众门户待办提醒接口

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#74]
1.	信息提示及推送范围及内容
门户电脑端
待办提示内容：收付款计划提醒、任务提醒
操作模式：用户登陆后在待办提示中有数字提示，进入待办后可以看到提示文字，点击文字进入相应的数据台账。
门户手机端
推送提示：收付款计划提醒、任务提醒、开票提醒
操作模式：定时推送消息，无需点击后进入查看。
2.	接口模式
单独登陆：沿用原先和审批中心的单独登陆模式。
消息接口：由华炎提供ODATA接口及接口说明，提示信息盟拓根据提示语（待客户确认）内容通过ODATA接口查询后组成。
电脑端的提示信息，在用户登陆时进行查询并显示。
手机端的推送提示，由盟拓制作定时器，每天早上9点取信息进行推送。

**Comment by huangyiirene** [comment]
提示语为“付款提醒：{合同名称+计划付款日期+本次付款金额}”

**Comment by baozhoutao** [comment]
推送相关对象的定义文档：https://github.com/steedos/steedos-project-dzug/tree/master/docs/objects
odata接口使用说明：https://developer.steedos.com/docs/en/odata_query/
