### ISSUE TITLE
房屋租赁业务--确认收入规则

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#76]
1.	系统根据业务类型为房屋租赁（出租方）时，业财台账“确认收入”子表权限对财务人员开放，经办人不能填写。在相应合同下的“确认收入”子表中由财务人员录入确认收入的金额和相关信息，点击“确认收入”按钮。系统根据财务人员所填写的确认收入信息，在“应收记录”子表中自动生成记录。点击记录可以查看到具体内容，点击“申请开票”按钮，将信息传输到NC系统，在NC系统中生成应收单。财务人员维护好相关财务核算信息，审批完成后。NC审批过程信息、审批状态等信息会定时回传至相应的业财台账应收信息中。
2.	业财台账中，由经办人员在“房屋租赁申请开票”子表中录入申请开票信息，点击“生成应付记录”按钮，业财台账系统判断历史确认收入金额与历史申请开票金额，历史申请开票金额小于等于历史确认收入金额，不生成应付记录；历史申请开票金额大于历史确认收入金额，差额部分在“应付记录”子表中生成记录，在应收记录中经办人员可以维护结算方式等信息，完成后点击“申请开票”按钮，自动推送形成NC应收单据，并进入审批状态。财务人员维护好相关财务核算信息，审批完成后，可以对应收单进行实际开票操作。NC审批过程信息、审批状态、开票信息、开票状态等信息会实时回传至相应的业财台账应收信息中。

**Comment by sunhaolin** [comment]
- 确认收入增加字段 历史确认收入总金额
- 房屋租赁开票 申请开票金额字段值=单价*数量
- 合同下的历史申请开票金额/历史已完成开票金额之和小于等于历史确认收入金额/历史确认收入总金额之和，不生成应付记录；历史申请开票金额/历史已完成开票金额之和大于历史确认收入金额/历史确认收入总金额之和，差额部分在“应收记录”子表中生成应收记录
