### ISSUE TITLE
房租租赁业务--确认成本规则

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#77]
1.	系统根据业务类型为房屋租赁（承租方）时，在相应合同下的“确认成本”子表中由财务人员录入确认成本的金额和相关信息，点击“生成应付记录”按钮。系统根据财务人员所填写的确认成本信息，在“应付记录”子表中自动生成记录。点击记录可以查看到具体内容，点击“收票”按钮，将信息传输到NC系统，自动推送形成NC应付单据，并进入审批状态。财务人员维护好相关财务核算信息，点击“审核”按钮。NC应付单据信息会实时回传至相应的OA应付信息中。
2.	房屋租赁收票时，在相应合同下的“收票记录”子表中，由业务人员点击“上传发票”进行附件上传。在发票记录中点击“生成应付单”按钮，系统将对发票总金额和已确认成本/费用总金额进行对比后差额生成应付记录。对于无需生成应收记录，系统会给予提示。在生成的应付记录上，业务人员可以维护结算方式等数据，完成后点击“收票”，数据传输到NC系统，自动推送形成NC应付单据，并进入审批状态。财务人员维护好相关财务核算信息，点击“审核”按钮。NC应付单据信息会实时回传至相应的OA应付信息中。
3.	业财台账的付款记录中，由业务人员录入付款信息，点击“关联发票”按钮，进行发票选择后关联，点击“付款”按钮，自动推送形成NC付款单据，传输发票附件到NC，并进入审批环节。

**Comment by sunhaolin** [comment]
- 付款单位、收款单位、币种由合同带出

**Comment by sunhaolin** [comment]
- 确认成本中点击 生成应付记录按钮 弹出的应付记录界面的 付款发票字段不应该必填
- 付款发票中合同类型是 房屋租赁（承租）时 才显示 生成应付记录按钮
- 付款发票列表 点击 生成应付记录按钮的时候，计算出的应付金额应该只读，付款发票字段应该必填

**Comment by sunhaolin** [comment]
- 付款发票增加字段 历史收票总金额（第一次填发票时填写）
- 确认成本增加字段 历史已确认成本
- 将合同下的所有发票的总金额/历史收票总金额之和减去确认成本中的确认成本/历史已确认成本之和所得差额作为应付记录的应付金额(money)字段
- 应付记录的 历史收票总金额字段 由付款发票中的 历史收票总金额赋值
