### ISSUE TITLE
业财台账首页需添加按钮（NC审批流程图），点击后弹出页面显示流程图（图片格式）

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#78]

**Comment by hotlong** [comment]
在 webapp/public 文件夹下写一个静态网页

**Comment by baozhoutao** [comment]
方案：请在项目下新建public文件夹， 放入NC审批流程图。 在首页通过window.open(‘图片地址’)的方式查看图片。

**Comment by yinlianghui** [comment]
已经加到顶部导航中了，点击链接可以弹出图片，图片路径为项目源码的`public/nc/workflow.jpg`，用的是测试的图片，后续可以用正式图片来替换
