### ISSUE TITLE
估算利息工具

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#79]
财务人员可填写计息开始时间、计息结束时间、本金、税率（年利率）等数据，根据计财部提供的计算公式：
利息=本金 * 利率 * （计息开始日期-计息结束日期+1）/365

**Comment by hotlong** [comment]
在 webapp/public 文件夹下写一个静态网页

**Comment by baozhoutao** [comment]
路径： {project_root_url}/tools/imputed_interest.html
