### ISSUE TITLE
台账信息页面中的子表顺序需调整

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#93]
付款计划
付款发票
应付记录
付款记录
收款计划
应收记录
收款记录
确认收入
房屋租赁开票
确认成本
日程

**Comment by sunhaolin** [comment]
需要新版creator打包  6434577513fe350b7c11a62f496bcb88907dc8b6

**Comment by sunhaolin** [comment]
已使用"steedos-server": "1.18.0"
